{
 "title": "Business-metrics",
 "description": "Dashboard for Resource-service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": "label_values(jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Business", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logged-in users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "targets": [
    { "expr": "user_gauge", "legendFormat": "users" }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum by (uri, status, method)(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"2.*\", uri!~\".*/actuator/.*|.*/swagger.*|.*/webjars/.*|.*root.*|.*api-docs.*\"}[1m]))",
     "legendFormat": "{{method}} {{uri}} status={{status}} "
    }
   ]
  },
  {
   "title": "Login Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum by (result)(rate(login_counter_total{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "{{result}}"
    }
   ]
  }
 ]
}