spring:
  application:
    name: resource-service
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: test
      username: test
      password: test

server:
  port: 9000
  http2:
    enabled: true

#добавить хранилище
jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==

logging:
  level:
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG


springdoc:
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
  api-docs:
    path: /swagger-doc/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus